# Site settings
title: OpenMapKit Server
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "omk/pages" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

destination: "../pages"

keep_files: [id]

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Forms
    link: /omk/pages/forms
  option2:
    name: Upload Form
    link: /omk/pages/upload-form/


# Build settings
markdown: kramdown
